stages:
  - stage: buildstage
    displayName: dotnetbuild 
    jobs:
      - job: dotnetbuildjob
        displayName: build job dotnet
        steps:
          - script: dotnet restore
            displayName: restore 
          - script: dotnet build 
            displayName: build app
          - script: dotnet test 
            displayName: test
          - script: dotnet publish
            displayName: publish 